version: '3'
services:
  my-java-app:
    image: 139.59.157.150:8085/java-app:1.2-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
    container_name: my-java-app
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 8083:80
    depends_on:
      - mysql
    container_name: phpmyadmin
volumes:
  mysql_data:
    driver: local

